name: publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-pnpm
        uses: pnpm/action-setup@v4

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: install
        run: pnpm install --frozen-lockfile

      - name: typecheck
        run: pnpm typecheck

      - name: test
        run: pnpm test

      - name: check
        run: pnpm check

      - name: build
        run: pnpm -r build

      - name: publish
        run: pnpm publish -r --access public --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
